### ISSUE TITLE
Recommendation or multiclassification? Why?

### ISSUE THREAD

**Issue by imranbozaci** [ITU-Apollo/Data-analytics#11]
@samozturk @hcipek @simgeco @senasa21 @alpsah @imranbozaci

**Comment by simgeco** [comment]
Selam,  
Daha onceden literaturden ornek calismalar oldugu icin classification'a agirlik vermemiz gerektigini dusunuyorum. Recommendation'da biraz yolumuzu bulmakta gucluk cekebiliriz. Classification'da daha rahat ederiz elimizde metodoloji oldugu icin. Yeni bir yol yordam bulursak da literature katkisi olur. Yeni bir sey yapmak icin cok fazla vaktimiz yok :) 

Recommendation namina en fazla beraber kullanilacak kutuphaneleri filan onerebiliriz, cok fazla ileri gidemeyiz. Belki ucundan kiyisindan ona girisiriz vaktimiz kalirsa. 

CC: @imranbozaci

**Comment by samozturk** [comment]
Classification yapip, recommender kismini descriptive olarak birakabiliriz simgenin de dedigi gibi. bir dashboard'da kutuphane girildigi zaman, onunla beraber en cok kullanilan 3-5 kutuphaneyi cikartabiliriz.

Diyorum ki, classificationi yapistiralim ilk basta, hakan sukur'un guney koreye attigi gol gibi. Sonra isteyen bunun ustune yatar, isteyen recommendation'i da eklemek icin organiz olup calisir. Hocaya da "hocam biz language predict ediyoruz ama bir de soyle bir sey ekledik ama henuz bitmedi" falan ayagi cekebiliriz.

**Comment by alpsah** [comment]
Bence classification tarafına doğru her türlü gideceğiz. İlk asamadaki datayi nihai elde edip process hızımızı görürsek diğer alternatiflere yönümüzü çevirebiliriz. Gün bitmeden yetisip ışın kılıcını gormekten kurtuldugum için mutesekkirim
