### ISSUE TITLE
Kibana Wordcloud (python, java)

### ISSUE THREAD

**Issue by imranbozaci** [ITU-Apollo/Data-analytics#18]

**Comment by simgeco** [comment]
@imranbozaci burada dosya bazinda wordcloud istiyoruz degil mi? (belki 1000 kere sormusumdur 🥲 )

**Comment by imranbozaci** [comment]
ses kaydı gönderdim sana:)
Simge ***@***.***>, 27 Mar 2022 Paz, 14:02 tarihinde şunu
yazdı:
