### ISSUE TITLE
Spark---her bir file için her bir dilde libraries analiz

### ISSUE THREAD

**Issue by imranbozaci** [ITU-Apollo/Data-analytics#19]
count, mean,sd, max, min

**Comment by senasa21** [comment]
Phyton için kütüphane sayıları EMR'da çalıştırıldı. S3'e json formatında atıldı. Kodda birkaç düzletme yapıp datayı düzeltmem gerek. Kibana'da görselleştirme kısmında desteğe ihtiyacım olacak.
