### ISSUE TITLE
Snippetların birleştirilmesi

### ISSUE THREAD

**Issue by imranbozaci** [ITU-Apollo/Data-analytics#5]

**Comment by imranbozaci** [comment]
Deadline:Bu hafta cumartesi @alpsah @samozturk uygun mudur?
her taska iki kişi ekliyorum efektif takip edelim diye

**Comment by samozturk** [comment]
commit_hash uzerinden birlestirilecek. baslangicta bunu tek bir csv icin yapan bir kod yazabilirsek hepsine uygulariz. Ozellikle kucuk boyutlu dosyalar uzerinde calismak buyuk kolaylik saglar.
Boyutlari elde etmek icin `du -sh ~/data/*` komutunu kullandim. Ciktilari su sekilde:

> 3.3M	bash.csv
3.9G	clang.csv
2.2G	cpp.csv
4.0K	db.sh
2.6G	golang.csv
3.0G	java.csv
3.2G	javascript.csv
2.4G	json.csv
200M	jupyter.csv
1.2G	markdown.csv
22G	merged.csv
1.4G	python.csv
350M	ruby.csv
191M	rust.csv
124M	shell.csv
210M	yaml.csv

**Comment by hcipek** [comment]
C - InProgress,
C++ - Ready to Process
Go - Ready to Process
Java - Done
Javascript - Ready to Process
Json - Done
Jupyter - Ready to Process
Markdown - Done
Python - Done
Ruby - Done
Rust - Done
Shell - Done
Yaml - Done

**Comment by hcipek** [comment]
Javada yaklaşık 7.5M snippet vardı, total 11 saat civarında birleştirme tamamlandı.
C de 12M snippet var (tahmini 18 saat)
Javascript 9M (tahmini 13 saat)
C++ 6.5M (tahmini 9 saat)
Go 8M (tahmini 12 saat)
Jupyter 245k (20 dakika)

Estimation Cumartesi Ögleden önce/sonra

**Comment by hcipek** [comment]
Repo Bilgileri
Estimation : Cumartesi Akşam/Gece
